- name: Check if dynamic group variable exists
  hosts: localhost
  vars_files:
    - vars/main.yml
  vars:
    group_variable_name: "group_variable"  # Name of the variable to check

  tasks:
    - name: Check if dynamic 'group_variable' exists
      debug:
        msg: "The variable '{{ group_variable_name }}' is defined!"
      when: lookup('vars', group_variable_name | default(None)) is not none

    - name: Skip task if dynamic 'group_variable' is not defined
      debug:
        msg: "The variable '{{ group_variable_name }}' is not defined, skipping task."
      when: lookup('vars', group_variable_name | default(None)) is none
